# Schema for the configuration files of the Webtheme theme.
webtheme.settings:
  type: theme_settings
  label: "Webtheme settings"
  mapping:
    uikit_source:
      type: string
      label: "UIkit library source"
    navbar_sticky:
      type: boolean
      label: "Sticky navbar"
    htmx_navigation:
      type: boolean
      label: "HTMX navigation"
